# Generated by Django 4.2.6 on 2023-12-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_alter_apartment_parking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Land_plot',
            new_name='LandPlot',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='rus_name',
            new_name='name_adv',
        ),
        migrations.AlterField(
            model_name='room',
            name='building_type',
            field=models.CharField(blank=True, choices=[(None, 'Выбрать'), ('Кирпичный', 'Кирпичный'), ('Блочный', 'Блочный'), ('Монолитный', 'Монолитный'), ('Панельный', 'Панельный'), ('Монолитно-кирпичный', 'Монолитно-кирпичный')], max_length=30, null=True, verbose_name='Тип дома'),
        ),
    ]
